export interface IWebHookText {
  object: string;
  entry:  Entry[];
}

export interface Entry {
  id:      string;
  changes: Change[];
}

export interface Change {
  value: Value;
  field: string;
}

export interface Value {
  messaging_product: string;
  metadata:          Metadata;
  contacts:          Contact[];
  messages:          Message[];
}

export interface Contact {
  profile: Profile;
  wa_id:   string;
}

export interface Profile {
  name: string;
}

export interface Message {
  from:      string;
  id:        string;
  timestamp: string;
  text?:      Text;
  document?:  MediaType;
  image?:     MediaType;
  video?:     MediaType;
  audio?:     MediaType;
  type:      'text' | 'document' | 'image' | 'video' | 'audio';
}

export interface Text {
  body: string;
}

export interface Metadata {
  display_phone_number: string;
  phone_number_id:      string;
}

export default IWebHookText;
// Generated by https://quicktype.io

export interface MediaType {
  filename?:  string;
  mime_type: string;
  sha256:    string;
  id:        string;
  caption?:  string;
  voice?:    boolean;
}

// export interface IImageType {
//   mime_type: string;
//   sha256:    string;
//   id:        string;
//   caption?:  string;
// }

